#!/bin/bash
set -euo pipefail

# Generates PR body for workflow deployment
# Usage: generate-pr-body.sh <target-branch> <automation-core-ref> <github-sha> <github-actor>
# Output: Prints PR body to stdout

TARGET_BRANCH="$1"
AUTOMATION_CORE_REF="$2"
GITHUB_SHA="$3"
GITHUB_ACTOR="$4"

cat <<EOF
**Automated deployment of automation-core workflows**

## Configuration
- **Automation-core ref**: \`@${AUTOMATION_CORE_REF}\`
- **Target branch**: \`${TARGET_BRANCH}\`

## Changes
This PR updates the GitHub Actions workflows from automation-core templates.

## Source
- Automation-core commit: \`${GITHUB_SHA:0:7}\`
- Deployed by: @${GITHUB_ACTOR}

---
🤖 Generated by automation-core workflow deployment
EOF
