---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubectlTest.fullname" . }}-patch-sa
  namespace: {{ template "kubectlTest.namespace" . }}
  labels: {{ include "kubectlTest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubectlTest.fullname" . }}-patch-sa
  labels: {{ include "kubectlTest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubectlTest.fullname" . }}-patch-sa
  labels: {{ include "kubectlTest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubectlTest.fullname" . }}-patch-sa
subjects:
  - kind: ServiceAccount
    name: {{ include "kubectlTest.fullname" . }}-patch-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubectlTest.fullname" . }}-patch-sa
  namespace: {{ template "kubectlTest.namespace" . }}
  labels: {{ include "kubectlTest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ include "kubectlTest.fullname" . }}-patch-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/os: linux
        {{- if .Values.nodeSelector }}
        {{ toYaml .Values.nodeSelector | indent 8 }}
        {{- end }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
        {{- if .Values.tolerations }}
        {{ toYaml .Values.tolerations | indent 8 }}
        {{- end }}
      containers:
        - name: {{ include "kubectlTest.fullname" . }}-patch-sa
          image: {{ include "system_default_registry" . }}{{ .Values.global.kubectl.repository }}:{{ .Values.global.kubectl.tag }}
          imagePullPolicy: IfNotPresent
          command: ["kubectl", "-n", {{ .Release.Namespace | quote }}, "patch", "serviceaccount", "default", "-p", "{\"automountServiceAccountToken\": false}"]
