---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubectlTest.fullname" . }}-upgrade
  namespace: {{ include "kubectlTest.namespace" . }}
  labels: {{ include "kubectlTest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubectlTest.fullname" . }}-upgrade
  namespace: {{ template "kubectlTest.namespace" . }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "0"
data:
{{ (.Files.Glob "files/upgrade/scripts/*").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kubectlTest.fullname" . }}-upgrade
  namespace: {{ template "kubectlTest.namespace" . }}
  labels:
    app: {{ template "kubectlTest.fullname" . }}-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade, pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      name: {{ template "kubectlTest.fullname" . }}-upgrade
      labels:
        app: {{ template "kubectlTest.fullname" . }}-upgrade
    spec:
      serviceAccountName: {{ template "kubectlTest.fullname" . }}-upgrade
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/os: linux
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
      containers:
        - name: run-scripts
          image: {{ template "kubectl.image" . }}
          imagePullPolicy: {{ .Values.global.kubectl.pullPolicy | default "Always" }}
          {{- if and .Values.global.kubectl (hasKey .Values.global.kubectl "kuberlrAllowDownload") }}
          env:
            - name: KUBERLR_ALLOWDOWNLOAD
              value: {{ default .Values.global.kubectl.kuberlrAllowDownload false }}
          {{- end }}
          command:
            - /bin/sh
            - -c
            - >
              sleep 10;
              for s in $(find /etc/scripts -type f); do
                echo "Running $s...";
                cat $s | bash
              done;
          volumeMounts:
            - name: upgrade
              mountPath: /etc/scripts
      volumes:
        - name: upgrade
          configMap:
            name: {{ template "kubectlTest.fullname" . }}-upgrade
