global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    image:
      repository: rancher/kuberlr-kubectl
      tag: ''
      pullPolicy: "IfNotPresent"
    # As long as kubectl image is using `rancher/kuberlr-kubectl` it can use kuberlr features.
    # kuberlrAllowDownload is disabled by default for most compatibility with air-gaps
    # When enabled it will allow kuberlr to download a compatible `kubectl` with the target cluster.
    # kuberlrAllowDownload: false