#!/bin/bash
set -e

if ! hash helm 2>/dev/null; then
    echo "Helm is not installed"
    exit 1
fi

source "$(dirname "$0")/version"
source "$(dirname "$0")/util-chart"
#source "$(dirname "$0")/util-team-charts"

cd "$(dirname "$0")/.."

echo "Preparing Kuberlr-Kuebctl testing chart"
clean-old-charts
cp -rf charts build/

if [[ "$REPO" != "rancher" ]]; then
  echo "Using custom repo: $REPO to build chart"
  edit-chart ./build/charts/kuberlr-kubectl-test/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}" "${REPO}"
else
  edit-chart ./build/charts/kuberlr-kubectl-test/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
fi
if ! package-chart ./build/charts/kuberlr-kubectl-test ./build/charts ; then
  echo "package-chart failed..."
  exit 1
fi