name: Branch head Prerelease Images

on:
  push:
    branches:
      - main
      - release/v[0-9]+.x

permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write

jobs:
  build:
    uses: rancher/kuberlr-kubectl/.github/workflows/head-build.yml@automation-core
