name: Stable Image Releases

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write

jobs:
  release:
    uses: rancher/kuberlr-kubectl/.github/workflows/release.yml@automation-core
